# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "RecipeMash" do

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'

end

target "RecipeMashTests" do

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'

end

